apiVersion: batch/v1
kind: Job
metadata:
  name: rsync-nfs-to-filestore-full-20201024
  namespace: tfwiki-dev
spec:
  template:
    spec:
      containers:
        - name: rsync-nfs-to-filestore-full
          image: instrumentisto/rsync-ssh
          command: ["rsync"]
          args:
            [
              "-aPhW",
              "--no-compress",
              "--inplace",
              # "--exclude", "archive",
              # "--exclude", "thumb",
              # "--exclude", "deleted",
              "/images-nfs/",
              "/images-filestore/",
            ]
          volumeMounts:
            - mountPath: /images-filestore
              name: filestore-images
              subPath: dev
            - mountPath: /images-nfs
              name: nfs-images
      volumes:
        - name: filestore-images
          persistentVolumeClaim:
            claimName: tfwiki-media-dev-claim
        - name: nfs-images
          persistentVolumeClaim:
            claimName: nfs-dev
      restartPolicy: Never
