apiVersion: v1
kind: ConfigMap
metadata:
  name: mediawiki-config
data:
  memcached_host: memcached
  server_url: https://prod.wiki.tf
  sitename: (Production) Team Fortress Wiki
  varnish_host: varnish
  blackfire_socket: tcp://blackfire:8707